<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <SpaRoot>ClientApp</SpaRoot>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
        <SatelliteResourceLanguage>en</SatelliteResourceLanguage>
        <UserSecretsId>1dd97ef2-49af-40fc-a48a-8a0331e336b5</UserSecretsId>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <NoWarn>1701;1702;CS1591</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <NoWarn>1701;1702;CS1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Lamar" Version="15.0.1" />
        <PackageReference Include="Lamar.Microsoft.DependencyInjection" Version="15.0.1" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.1" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
        <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="10.0.1" />
        <PackageReference Include="Microsoft.Graph" Version="5.99.0" />
        <PackageReference Include="Microsoft.Identity.Client" Version="4.83.3" />
        <PackageReference Include="Microsoft.Identity.Web" Version="4.2.0" />
        <PackageReference Include="Microsoft.Identity.Web.GraphServiceClient" Version="4.2.0" />
        <PackageReference Include="NameGenerator" Version="2.0.4" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="Serilog" Version="4.3.0" />
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
        <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
        <PackageReference Include="Serilog.Exceptions" Version="8.4.0" />
        <PackageReference Include="Serilog.Exceptions.SqlServer" Version="8.4.0" />
        <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
        <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.0" />
        <PackageReference Include="Serilog.Sinks.ApplicationInsights" Version="4.1.0" />
        <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
        <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
        <PackageReference Include="Serilog.Sinks.EventLog" Version="4.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="9.0.2" />
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.0" />
        <PackageReference Include="Swashbuckle.AspNetCore.Newtonsoft" Version="10.1.0" />
        <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../Broadcaster.Business/Broadcaster.Business.csproj" />
        <ProjectReference Include="../Broadcaster.Stream/Broadcaster.Stream.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="$(SpaRoot)/**/*.*">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
